server:
  port: 8081
  servlet:
    context-path: /whale

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.180.144:3306/morning?useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false
  session:
    store-type: none
  resources:
    static-locations: classpath:/static/

whale:
  security:
    browser:
      loginPage: /demo-signIn.html
      loginType: JSON #REDIRECT
    code:
      image:
        length: 4
        url: /whale/hello